name: 'Build'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.event.pull_request.head.sha || github.sha }}
    secrets:
      USAGE_REPORTING_TESTS_SECRET_KEY: ${{ secrets.DEMO_COMPANY_SECRET_KEY }}
      CORE_V2_API_SECRET: ${{ secrets.CORE_V2_STAGING_NA_SYSTEM_API_SECRET }}
